{% set name = "healpy" %}
{% set version = "1.11.0" %}
{% set sha256 = "8c3c7982ae188549315a11f4d1aa6528cd1ccf078017ca20120ff2cf1b47babe" %}

package:
    name: {{ name|lower }}
    version: {{version}}

source:
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record record.txt
    skip: True  # [win]

requirements:
    build:
        - python
        - setuptools
        - pkg-config
        - toolchain
        - numpy 1.7.*  # [py27]
        - numpy 1.9.*  # [py35]
        - numpy 1.11.*  # [py36]
        - pytest-runner
    run:
        - python
        - matplotlib
        - numpy >=1.7  # [py27]
        - numpy >=1.9  # [py35]
        - numpy >=1.11  # [py36]
        - six
        - astropy
        - pytest-runner

test:
    imports:
        - healpy
        - healpy.test
    requires:
        - pytest
        - nose

about:
    home: http://github.com/healpy
    license: GPL-2.0
    summary: Healpix tools package for Python

extra:
    recipe-maintainers:
        - lpsinger
        - mwcraig
        - pkgw
        - zonca
