{% set version = "1.11.0" %}

package:
    name: healpy
    version: {{version}}

source:
    fn: healpy-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/h/healpy/healpy-{{ version }}.tar.gz
    md5: c30daf225b3173224d6ea0cb10714b87

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt
    skip: True  # [win]

requirements:
    build:
        - python
        - setuptools
        - numpy x.x
        - pkg-config
        - pytest-runner

    run:
        - python
        - matplotlib
        - numpy x.x
        - six
        - astropy
        - pytest-runner

test:
    imports:
        - healpy
        - healpy.test
    requires:
        - pytest
        - nose

about:
    home: http://github.com/healpy
    license: GPL-2.0
    summary: Healpix tools package for Python

extra:
    recipe-maintainers:
        - mwcraig
        - zonca
        - lpsinger
