travis:
  secure:
    BINSTAR_TOKEN: OYWHEH7ajGQWRzMH2INZl6pzwvMustvg1kLhy7dktRDPjubZJQfqmy2f8IlDvTMopv2tYkgu+HROvnVf5sjl37lEcSqZi/PkawP4REwkYjl+cR89X/61HVmIihRE66Gj2ddrCxoVWnJWZKBav0ajyINTJlxcHwnjvmDG9tn6LEhgiCPlX4BkkFrahnOO3ZNGBR2CCCeasNOt0DcqhETO62Dxsr+uOJoA74JmUy5IQH+T1IS67NG2IWTOebaz1OETOYSGelnVRa98DpzPiubg6HHnb03Suj7OaNVlFt0Gl+a0gtqLWsUtEaCiZmAkI3hdtHnHvcdC91x9G2e47nSsUs47AgPK2UVQON9oW0pVFnXBgBISoNQVkOUdcWu7qFBxOLcNUcDPsYJV62TdPuCEpacJdp9v9hdkdF+E50FJMslfzNRZfX+vHVBSY5qtO0GbxovihBb4fv/2jBkg0tvL/tmn6WKnX1VqRaJvj7QQ93V1wyWo/pcx+7PT4QC0BWaPPIEIcF5WD2KvDBQim5Tbr5zRmUhowJt/r97KmHsSo25Fs9LGMaS9STHezTpeQIgQu7ZRv4l4hhU85pEEVOyvV04vY5hTVZMtI5EckGACHSmtQ+z1S3jcNjiZRQFtQJ5OU4VMQMU0cV5WvWXNkh9Dzz+DJCBQKZV5yKeLJl3U+Xw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
