travis:
  secure:
    BINSTAR_TOKEN: aWAfu8iKOqoRunHjUXfdCtALLeFG1ahS27sq7liZBNxF7BUQFdSTvn/2G4ekh1T3Q/BbhJsbsM/xGiTlv/k0JwPuSc/9pt+x0MOi27FFMeB/guSqLYYabV6Hp+yc25E3lGil7lJ7zdvofrm23H9xb/lSPeXXVAVM/db3j+BWoJ6auTbw5tdm+mAM2ubY9gJtWj1mbvwgUyhB0RPBj6GCI5UCzqzRp8PAvhr9mE0u5ww6zWBW/xEXOjP/3HbWhInroywu/3W5A3CS4FcYSP6iRfbwtfyTafO4IVewiPiEG3WOgMiBbz6M83evT7N9O4hDnyCHfpXhQoTh2uZ8Eljn7FPK5LAUJZveyaiyioaUs7pCR4Qc7z2mb/v/rdFWQwhZlPO0p9c7UAecuTcidlNhJTfYZ1qRxwQIA1ACyLs6awgRYxU85iOpSQxwrPQlNgsz45US9hEoYzrvd1RBrthWKO6e73n725FEkg63DyNvq03IrwLno0MIiNdXkwkKrvnVKCk8SU+za37yNEmdp3Pw3EjykgN82YVe39B+5oilxSS77eOTVg6zVxctACYRJ5omgE2EKf+nrK0rDTsHl2w+V4K2CLmjnsWqPkFmlDnK7zMtRzmuAkcN+EvuxlwXFWdbrzL/fAPkyqA3+llJNw7IgpQGoWd5AkCr2ESCedBQB28=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
